sudo: required #Anytime you use docker you need sudo permission
services:
    - docker
before_install:
    - docker build -t myapp -f Dockerfile.dev . #Builds docker file

script:
    - docker run myapp npm run test -- --watchAll=false

deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'docker1'
    env: 'Docker1-env'
    bucket_name: 'elasticbeanstalk-us-east-2-425535899823'
    bucket_path: 'portfolio1'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
