sudo: required #Anytime you use docker you need sudo permission
services:
    - docker
before_install:
    - docker build -t myapp -f Dockerfile.dev . #Builds docker file

script:
    - docker run myapp npm run test -- --watchAll=false
